FROM python:3

RUN apt-get update -y  && \
    apt-get install -y python3-venv python3-pip && \ 
    apt-get install -y python-dev

WORKDIR /app

RUN pip install Flask 

COPY . .

EXPOSE 5000

CMD [ "python", "./app.py" ]
